export const RESET_BUSINESS = 'RESET_BUSINESS'
export const SET_SERVER_DATA_LOADED = 'SET_SERVER_DATA_LOADED'

export const SET_INITIAL_CUSTOMER = 'SET_INITIAL_CUSTOMER'

export const ADD_INTEREST = 'ADD_INTEREST'
export const DELETE_INTEREST = 'DELETE_INTEREST'
export const UPDATE_INTEREST = 'UPDATE_INTEREST'
export const SELECT_INTERESTS = 'SELECT_INTERESTS'
export const EMPTY_INTERESTS = 'EMPTY_INTERESTS'
export const POPULATE_INTERESTS = 'POPULATE_INTERESTS'

export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const UPDATE_CUSTOMER = 'ADD_CUSTOMER'
export const SELECT_CUSTOMERS = 'SELECT_CUSTOMERS'
export const EMPTY_CUSTOMERS = 'EMPTY_CUSTOMER'
export const POPULATE_CUSTOMERS = 'POPULATE_CUSTOMERS'

export const ADD_MOTIVATION = 'ADD_MOTIVATION'
export const DELETE_MOTIVATION = 'DELETE_MOTIVATION'
export const UPDATE_MOTIVATION = 'UPDATE_MOTIVATION'
export const SELECT_MOTIVATIONS = 'SELECT_MOTIVATIONS'
export const EMPTY_MOTIVATIONS = 'EMPTY_MOTIVATIONS'
export const POPULATE_MOTIVATIONS = 'POPULATE_MOTIVATIONS'



export const ADD_STRUGGLE = 'ADD_STRUGGLE'
export const DELETE_STRUGGLE = 'DELETE_STRUGGLE'
export const UPDATE_STRUGGLE = 'UPDATE_STRUGGLE'
export const SELECT_STRUGGLES = 'SELECT_STRUGGLES'
export const EMPTY_STRUGGLES = 'EMPTY_STRUGGLES'
export const POPULATE_STRUGGLES = 'POPULATE_STRUGGLES'

export const ADD_VALUE = 'ADD_VALUE'
export const DELETE_VALUE = 'DELETE_VALUE'
export const UPDATE_VALUE = 'UPDATE_VALUE'
export const SELECT_VALUES = 'SELECT_VALUES'
export const EMPTY_VALUES = 'EMPTY_VALUES'
export const POPULATE_VALUES = 'POPULATE_VALUES'

export const ADD_SPECIFICATION = 'ADD_SPECIFICATION'
export const DELETE_SPECIFICATION = 'DELETE_SPECIFICATION'
export const UPDATE_SPECIFICATION = 'UPDATE_SPECIFICATION'
export const SELECT_SPECIFICATIONS = 'SELECT_SPECIFICATIONS'
export const EMPTY_SPECIFICATIONS = 'EMPTY_SPECIFICATIONS'
export const POPULATE_SPECIFICATIONS = 'POPULATE_SPECIFICATIONS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS'
export const EMPTY_PRODUCTS = 'EMPTY_PRODUCTS'
export const POPULATE_PRODUCTS = 'POPULATE_PRODUCTS'

export const ADD_FINAL_CUSTOMER = 'ADD_FINAL_CUSTOMER'
export const DELETE_FINAL_CUSTOMER = 'DELETE_FINAL_CUSTOMER'
export const UPDATE_FINAL_CUSTOMER = 'UPDATE_FINAL_CUSTOMER'

export const ADD_FINAL_USP = 'ADD_FINAL_USP'
export const DELETE_FINAL_USP = 'DELETE_FINAL_USP'
export const UPDATE_FINAL_USP = 'UPDATE_FINAL_USP'

export const ADD_FINAL_PRODUCT = 'ADD_FINAL_PRODUCT'
export const DELETE_FINAL_PRODUCT = 'ADD_FINAL_PRODUCT'
export const UPDATE_FINAL_PRODUCT = 'ADD_FINAL_PRODUCT'

export const ADD_FINAL_MISSION_STATEMENT = 'ADD_FINAL_MISSION_STATEMENT'
export const DELETE_FINAL_MISSION_STATEMENT = 'ADD_FINAL_MISSION_STATEMENT'
export const UPDATE_FINAL_MISSION_STATEMENT = 'ADD_FINAL_MISSION_STATEMENT'


export const ADD_BUSINESS_NAME = 'ADD_BUSINESS_NAME'
export const DELETE_BUSINESS_NAME = 'DELETE_BUSINESS_NAME'
export const UPDATE_BUSINESS_NAME = 'UPDATE_BUSINESS_NAME'

export const START_EDIT_MODE = 'START_EDIT_MODE'
export const STOP_EDIT_MODE = 'STOP_EDIT_MODE'

export const CHOOSE_NICHE = 'CHOOSE_NICHE'


//          User


export const ADD_FIREBASE_ID = 'ADD_FIREBASE_ID'
export const ADD_CUSTOMER_EMAIL = 'ADD_CUSTOMER_EMAIL'
export const ADD_CUSTOMER_SESSION_ID = 'ADD_CUSTOMER_SESSION_ID'
export const CUSTOMER_PURCHASE_SUCCESSFUL = 'CUSTOMER_PURCHASE_SUCCESSFUL'
export const CUSTOMER_PURCHASE_FAILED = 'CUSTOMER_PURCHASE_FAILED'
export const ADD_CUSTOMER_NAME = 'ADD_CUSTOMER_NAME'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const ADD_BUSINESS_IDS = 'ADD_BUSINESS_IDS'
export const SET_USER_ID = 'SET_USER_ID'
